

spring:
  application:
    name: huiyi
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/huiyi
    username: postgres
    password: sa123
    jpa:
      show-sql: true
      database: postgresql
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
          temp:
            use_jdbc_metadata_defaults: false

server:
  port: 8888

